  # This is a basic workflow to help you get started with Actions

name: Deploy to prod
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-prod:
    runs-on: ubuntu-18.04
    name: Deploy to Production
    steps: 
      - uses: chrnorm/deployment-action@releases/v1
        name: Create prod deployment
        id: deployment_prod
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: Production
      - name: Running production deployment
        run: |
          echo Deploying to production...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update prod deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_prod.outputs.deployment_id }}
