# This is a basic workflow to help you get started with Actions

name: Deploy to test and staging
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-staging:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    name: Deploy to Staging
    needs: [deploy-to-test]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create staging deployment
        id: deployment_staging
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: Staging
      - name: Running staging deployment
        run: |
          echo Deploying to staging...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update staging deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_staging.outputs.deployment_id }}
  deploy-to-test:
    runs-on: ubuntu-18.04
    name: Deploy to test
    steps: 
      - uses: chrnorm/deployment-action@releases/v1
        name: Create test deployment
        id: deployment_test
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: Test
      - name: Running test deployment
        run: |
          echo Deploying to test...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update test deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment_test.outputs.deployment_id }}
